apiVersion: v1
kind: Service
metadata:
  name: inventory-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: inventory-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-mysql
spec:
  serviceName: inventory-mysql
  replicas: 1
  selector:
    matchLabels:
      app: inventory-mysql
  template:
    metadata:
      labels:
        app: inventory-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
